apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: kursoversikt
    namespace: default
    labels:
        team: {{team}}
spec:
    image: {{version}}
    team: {{team}}
    port: 3000
    ingresses:
        - https://arbeidsgiver-q.nav.no/kursoversikt/
    liveness:
        path: /kursoversikt/internal/isAlive
        initialDelay: 20
    readiness:
        path: /kursoversikt/internal/isReady
        initialDelay: 20
    vault:
        enabled: true
    webproxy: true
    env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/ssl/ca-bundle.pem
