apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: kursoversikt
    namespace: default
    labels:
        team: teamtag
spec:
    image: navikt/kursoversikt:4fea50a8934f4ff0a62be486403ddbf452409d9b
    team: teamtag
    port: 3000
    ingresses:
        - https://arbeidsgiver.nav.no/kursoversikt/
    liveness:
        path: /kursoversikt/internal/isAlive
        initialDelay: 20
    readiness:
        path: /kursoversikt/internal/isReady
        initialDelay: 20
    vault:
        enabled: true
    webproxy: true
    env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/ssl/ca-bundle.pem
