apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: kursoversikt
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  team: fager
  port: 3000
  ingresses:
    - '{{{ingress}}}'
  liveness:
    path: /kursoversikt/internal/isAlive
    initialDelay: 20
  readiness:
    path: /kursoversikt/internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /kursoversikt/internal/metrics
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: SF_TARGET
      value: '{{{sfurl}}}'
    - name: SF_AUTH_URL
      value: '{{{sfauthurl}}}'
    - name: GIT_COMMIT
      value: {{commit}}
  envFrom:
    - secret: kursoversikt-secrets
  accessPolicy:
    outbound:
      rules:
        - application: kursoversikt
      external:
        - host: nav.pameldingssystem.no
        - host: www.nav.no
        - host: '{{{sfauthhost}}}'
        - host: '{{{sfhost}}}'