apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: kursoversikt
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  ingresses:
    - '{{{ingress}}}'
  liveness:
    path: arbeidsgiver/kursoversikt/internal/isAlive
    initialDelay: 20
  readiness:
    path: arbeidsgiver/kursoversikt/internal/isReady
    initialDelay: 20
  webproxy: true
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: SF_AUTH_TARGET
      value: '{{{sfauthtarget}}}'
    - name: SF_TARGET
      value: '{{{sfurl}}}'
    - name: SF_AUTH_BASE_URL
      value: '{{{sfauthbaseurl}}}'
  envFrom:
    - secret: pindena-pass
    - secret: pindena-user
    - secret: sfuser
    - secret: sfclientid
    - secret: sfpass
    - secret: sfsecuritytoken
  accessPolicy:
    outbound:
      external:
        - host: nav.pameldingssystem.no
        - host: www.nav.no
