version: 2.1
orbs:
  nais: navikt/nais-deployment@dev:master

jobs:
    build:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - restore_cache:
                  name: Hent Yarn cache
                  keys:
                      - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                  name: Installer avhengigheter
                  command: |
                      yarn install --frozen-lockfile
            - save_cache:
                  name: Lagre Yarn cache
                  key: yarn-packages-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn
            - run:
                  name: Bygg produksjonsversjon av React app
                  command: yarn build
            - nais/docker:
                image: navikt/kursoversikt

    deploy-til-dev:
      docker:
        - image: navikt/deployment-cli:0.4.2
      steps:
        - checkout
        - run:
            name: Unpack Private Key
            command: echo $GITHUB_PRIVATE_KEY | base64 -d > .circleci/github.key.pem
        - nais/deploy-with-gh-app:
            repo: navikt/kursoversikt
            image: navikt/kursoversikt
            github-app-id: 43789
            nais-template: nais-preprod.yaml
            environment: dev-sbs
            team: teamtag

    deploy-til-prod:
      docker:
        - image: navikt/deployment-cli:0.4.2
      steps:
        - checkout
        - run:
            name: Unpack Private Key
            command: echo $GITHUB_PRIVATE_KEY | base64 -d > .circleci/github.key.pem
        - nais/deploy-with-gh-app:
            repo: navikt/kursoversikt
            image: navikt/kursoversikt
            github-app-id: 43789
            nais-template: nais-prod.yaml
            environment: prod-sbs
            team: teamtag

workflows:
    version: 2.1
    bygg_og_deploy:
        jobs:
            - build:
                  context: NAIS deployment
            - deploy-til-dev:
                  context: tag-ci
                  requires:
                      - build
                  filters:
                      branches:
                          only:
                              - master
            # - godkjenn-til-prod:
            # type: approval
            # requires:
            # - build
            # filters:
            # branches:
            # only:
            # - master
            # - deploy-til-prod:
            # context: tag-ci
            # requires:
            # - godkjenn-til-prod
            # filters:
            # branches:
            # only:
            # - master
