name: Bygg branch

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  bygg:
    name: Bygg branch og lag deployment-issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: https://npm.pkg.github.com/
          cache: 'npm'

      - run:  npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - run:  npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        working-directory: ./server

      - run: npm run build

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/kursoversikt:${{ github.sha }}
            ghcr.io/${{ github.repository }}/kursoversikt:latest
          cache-from: type=registry,ref=${{ github.repository }}/kursoversikt:latest
          cache-to: type=inline
