on: workflow_dispatch

name: Deploy dev

jobs:
  deploy-dev-manual:
    name: deploy dev manual
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: "Deploy dev-gcp"
        uses: nais/deploy/actions/deploy@v1
        env:
          IMAGE: ghcr.io/${{ github.repository }}/kursoversikt:${{ github.sha }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/dev-gcp.yaml
          PRINT_PAYLOAD: true
          VAR: commit=${{ github.sha }}
          REF: ${{ github.sha }}
